### ISSUE TITLE
REPL does not run in Node 13

### ISSUE THREAD

**Issue by arabelladonna** [Hypercubed/f-flat_node#8]
Following the instructions from the Wiki, I attempted to run the version in the `next` branch in Node 13.12.0 on Windows 10 and it found 3217 vulnerabilities and failed to load.

Here is the output:

```
D:\Code\Fb>git clone -b next https://github.com/Hypercubed/f-flat_node.git
Cloning into 'f-flat_node'...
remote: Enumerating objects: 1704, done.
remote: Counting objects: 100% (1704/1704), done.
remote: Compressing objects: 100% (968/968), done.
remote: Total 4022 (delta 1267), reused 1115 (delta 720), pack-reused 2318
Receiving objects: 100% (4022/4022), 1.90 MiB | 8.19 MiB/s, done.
Resolving deltas: 100% (2928/2928), done.

D:\Code\Fb>cd f-flat_node

D:\Code\Fb\f-flat_node>npm install

> ohm-js@0.14.0 postinstall D:\Code\Fb\f-flat_node\node_modules\ohm-js
> node bin/dev-setup.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1291 packages from 532 contributors and audited 1205530 packages in 134.094s

36 packages are looking for funding
  run `npm fund` for details

found 3217 vulnerabilities (3202 low, 13 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

D:\Code\Fb\f-flat_node>npm start

> @hypercubed/f-flat@0.0.8 start D:\Code\Fb\f-flat_node
> tsc && node ./bin/repl.js

internal/modules/cjs/loader.js:616
            if (e.code !== 'ERR_PACKAGE_PATH_NOT_EXPORTED') throw e;
                                                            ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "commonjs/compose-regexp.js" defined in the package config /D:/Code/Fb/f-flat_node/node_modules/compose-regexp\package.json
    at resolveExportsTarget (internal/modules/cjs/loader.js:574:13)
    at resolveExportsTarget (internal/modules/cjs/loader.js:613:20)
    at applyExports (internal/modules/cjs/loader.js:503:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Code\Fb\f-flat_node\dist\utils\regex-logic.js:3:26) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hypercubed/f-flat@0.0.8 start: `tsc && node ./bin/repl.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @hypercubed/f-flat@0.0.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ari\AppData\Roaming\npm-cache\_logs\2020-04-06T17_21_15_460Z-debug.log

D:\Code\Fb\f-flat_node>
```

**Comment by Hypercubed** [comment]
Thank you for giving it a try... do you have the same issue with node v12?

**Comment by arabelladonna** [comment]
node v12 works. I went and installed Volta so I could manage node versions and it is working without issue. I'll go ahead and change the title of this issue.
